/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAbonnementsRouteImport } from './routes/_shell.abonnements'
import { Route as ShellActivitesRouteImport } from './routes/_shell.activites'
import { Route as ShellCaisseRouteImport } from './routes/_shell.caisse'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellNotificationsRouteImport } from './routes/_shell.notifications'
import { Route as ShellPaiementsRouteImport } from './routes/_shell.paiements'
import { Route as ShellParametresRouteImport } from './routes/_shell.parametres'
import { Route as ShellPlusRouteImport } from './routes/_shell.plus'
import { Route as ShellRappelsRouteImport } from './routes/_shell.rappels'
import { Route as ShellRecusRouteImport } from './routes/_shell.recus'
import { Route as ShellStatistiquesRouteImport } from './routes/_shell.statistiques'
import { Route as ShellMembresIndexRouteImport } from './routes/_shell.membres.index'
import { Route as ShellMembresMemberIdRouteImport } from './routes/_shell.membres.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAbonnementsRoute = ShellAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellActivitesRoute = ShellActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCaisseRoute = ShellCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPaiementsRoute = ShellPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => ShellRoute,
} as any)
const ShellParametresRoute = ShellParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlusRoute = ShellPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRappelsRoute = ShellRappelsRouteImport.update({
  id: '/rappels',
  path: '/rappels',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRecusRoute = ShellRecusRouteImport.update({
  id: '/recus',
  path: '/recus',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStatistiquesRoute = ShellStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembresIndexRoute = ShellMembresIndexRouteImport.update({
  id: '/membres/',
  path: '/membres/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMembresMemberIdRoute = ShellMembresMemberIdRouteImport.update({
  id: '/membres/$memberId',
  path: '/membres/$memberId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnements': typeof ShellAbonnementsRoute
  '/activites': typeof ShellActivitesRoute
  '/caisse': typeof ShellCaisseRoute
  '/dashboard': typeof ShellDashboardRoute
  '/notifications': typeof ShellNotificationsRoute
  '/paiements': typeof ShellPaiementsRoute
  '/parametres': typeof ShellParametresRoute
  '/plus': typeof ShellPlusRoute
  '/rappels': typeof ShellRappelsRoute
  '/recus': typeof ShellRecusRoute
  '/statistiques': typeof ShellStatistiquesRoute
  '/membres/$memberId': typeof ShellMembresMemberIdRoute
  '/membres/': typeof ShellMembresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnements': typeof ShellAbonnementsRoute
  '/activites': typeof ShellActivitesRoute
  '/caisse': typeof ShellCaisseRoute
  '/dashboard': typeof ShellDashboardRoute
  '/notifications': typeof ShellNotificationsRoute
  '/paiements': typeof ShellPaiementsRoute
  '/parametres': typeof ShellParametresRoute
  '/plus': typeof ShellPlusRoute
  '/rappels': typeof ShellRappelsRoute
  '/recus': typeof ShellRecusRoute
  '/statistiques': typeof ShellStatistiquesRoute
  '/membres/$memberId': typeof ShellMembresMemberIdRoute
  '/membres': typeof ShellMembresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/abonnements': typeof ShellAbonnementsRoute
  '/_shell/activites': typeof ShellActivitesRoute
  '/_shell/caisse': typeof ShellCaisseRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/paiements': typeof ShellPaiementsRoute
  '/_shell/parametres': typeof ShellParametresRoute
  '/_shell/plus': typeof ShellPlusRoute
  '/_shell/rappels': typeof ShellRappelsRoute
  '/_shell/recus': typeof ShellRecusRoute
  '/_shell/statistiques': typeof ShellStatistiquesRoute
  '/_shell/membres/$memberId': typeof ShellMembresMemberIdRoute
  '/_shell/membres/': typeof ShellMembresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnements'
    | '/activites'
    | '/caisse'
    | '/dashboard'
    | '/notifications'
    | '/paiements'
    | '/parametres'
    | '/plus'
    | '/rappels'
    | '/recus'
    | '/statistiques'
    | '/membres/$memberId'
    | '/membres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnements'
    | '/activites'
    | '/caisse'
    | '/dashboard'
    | '/notifications'
    | '/paiements'
    | '/parametres'
    | '/plus'
    | '/rappels'
    | '/recus'
    | '/statistiques'
    | '/membres/$memberId'
    | '/membres'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/abonnements'
    | '/_shell/activites'
    | '/_shell/caisse'
    | '/_shell/dashboard'
    | '/_shell/notifications'
    | '/_shell/paiements'
    | '/_shell/parametres'
    | '/_shell/plus'
    | '/_shell/rappels'
    | '/_shell/recus'
    | '/_shell/statistiques'
    | '/_shell/membres/$memberId'
    | '/_shell/membres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/abonnements': {
      id: '/_shell/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof ShellAbonnementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/activites': {
      id: '/_shell/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ShellActivitesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/caisse': {
      id: '/_shell/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof ShellCaisseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/paiements': {
      id: '/_shell/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof ShellPaiementsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/parametres': {
      id: '/_shell/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ShellParametresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/plus': {
      id: '/_shell/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof ShellPlusRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/rappels': {
      id: '/_shell/rappels'
      path: '/rappels'
      fullPath: '/rappels'
      preLoaderRoute: typeof ShellRappelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/recus': {
      id: '/_shell/recus'
      path: '/recus'
      fullPath: '/recus'
      preLoaderRoute: typeof ShellRecusRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/statistiques': {
      id: '/_shell/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof ShellStatistiquesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/membres/': {
      id: '/_shell/membres/'
      path: '/membres'
      fullPath: '/membres/'
      preLoaderRoute: typeof ShellMembresIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/membres/$memberId': {
      id: '/_shell/membres/$memberId'
      path: '/membres/$memberId'
      fullPath: '/membres/$memberId'
      preLoaderRoute: typeof ShellMembresMemberIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAbonnementsRoute: typeof ShellAbonnementsRoute
  ShellActivitesRoute: typeof ShellActivitesRoute
  ShellCaisseRoute: typeof ShellCaisseRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellPaiementsRoute: typeof ShellPaiementsRoute
  ShellParametresRoute: typeof ShellParametresRoute
  ShellPlusRoute: typeof ShellPlusRoute
  ShellRappelsRoute: typeof ShellRappelsRoute
  ShellRecusRoute: typeof ShellRecusRoute
  ShellStatistiquesRoute: typeof ShellStatistiquesRoute
  ShellMembresMemberIdRoute: typeof ShellMembresMemberIdRoute
  ShellMembresIndexRoute: typeof ShellMembresIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAbonnementsRoute: ShellAbonnementsRoute,
  ShellActivitesRoute: ShellActivitesRoute,
  ShellCaisseRoute: ShellCaisseRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellPaiementsRoute: ShellPaiementsRoute,
  ShellParametresRoute: ShellParametresRoute,
  ShellPlusRoute: ShellPlusRoute,
  ShellRappelsRoute: ShellRappelsRoute,
  ShellRecusRoute: ShellRecusRoute,
  ShellStatistiquesRoute: ShellStatistiquesRoute,
  ShellMembresMemberIdRoute: ShellMembresMemberIdRoute,
  ShellMembresIndexRoute: ShellMembresIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
